AllCops:
  # Exclude anything that isn't really part of our code.
  # rails_helper is excluded because it's full of solecisms, but it's mostly
  # generated code and copy-and-pasted snipets from READMEs.
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - '**/*.gemspec'
    - '**/Rakefile'
    - 'spec/**/*'
    - 'config/**/*'
    - 'app/models/forms/base.rb' # this is just too horrible
    - 'app/services/detainees/risk_mapper.rb'
    - 'app/form_builders/mps_form_builder.rb'
    - 'app/form_builders/errors_helper.rb'

# Prefer sensible naming to comments everywhere.
Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

# Just indent parameters by two spaces. It's less volatile if methods change,
# and there's less busy work lining things up.
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# Don't worry about the complexity of spec methods
Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/**/*'
    - 'app/models/risk.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/models/escort.rb'

Metrics/MethodLength:
  Max: 15
  Exclude:
    - 'app/form_builders/mps_form_builder.rb'
    - 'app/models/ability.rb'
    - 'app/services/detainees/details_mapper.rb'

Style/RescueStandardError:
  Enabled: false

# No-one in this team uses a fixed-width terminal
Metrics/LineLength:
  Max: 120

Naming/PredicateName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/IndentArray:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Security/Open:
  Exclude:
    - 'app/controllers/escorts/print_controller.rb'

Style/RegexpLiteral:
  Enabled: false
