source 'https://rubygems.org'

gem 'aws-sdk', '< 3.0'
gem 'cancancan'
gem 'connection_pool'
gem 'countries'
gem 'custom_error_message', git: 'https://github.com/thethanghn/custom-err-msg.git'
gem 'deep_cloneable'
gem 'excon'
gem 'faraday'
gem 'geckoboard-ruby'
gem 'govuk_elements_form_builder', git: 'https://github.com/ministryofjustice/govuk_elements_form_builder.git'
gem 'govuk_elements_rails'
gem 'govuk_frontend_toolkit'
gem 'govuk_template', '0.18.0'
gem 'jquery-rails'
gem 'logstasher'
gem 'omniauth-oauth2', '~> 1.3.1'
gem 'paperclip', '~> 5.1.0'
gem 'pg'
gem 'puma'
gem 'rails', '~> 5.1.4'
gem 'reform', '2.1.0'
gem 'reform-rails'
gem 'sass-rails', '~> 5.0'
gem 'sentry-raven'
gem 'slim-rails'
gem 'uglifier'
gem 'virtus'
gem 'wicked'
gem 'wicked_pdf'
gem 'wkhtmltopdf-binary'
gem 'zendesk_api'

group :development, :test do
  gem 'factory_bot_rails'
  gem 'faker'
  gem 'jasmine'
  gem 'jasmine-jquery-rails'
  gem 'pdftotext'
  gem 'pry-byebug'
  gem 'pry-rails'
end

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'listen', '~> 3.0.5'
  gem 'meta_request'
  gem 'rubocop', '~> 0.51.0', require: false
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  gem 'capybara'
  gem 'chromedriver-helper'
  gem 'climate_control'
  gem 'codeclimate-test-reporter', require: nil
  gem 'database_cleaner'
  gem 'diffy'
  gem 'launchy'
  gem 'rspec-its'
  gem 'rspec-rails'
  gem 'selenium-webdriver'
  gem 'shoulda-matchers'
  gem 'simplecov', require: false
  gem 'site_prism'
  gem 'webmock'
end
