apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.name" . }}
type: Opaque
data:
  GECKOBOARD_API_KEY: {{ .Values.secrets.GECKOBOARD_API_KEY | b64enc | quote }}
  GECKOBOARD_DATASET_PREFIX: {{ .Values.secrets.GECKOBOARD_DATASET_PREFIX | b64enc | quote }}
  SECRET_KEY_BASE: {{ .Values.secrets.SECRET_KEY_BASE | b64enc | quote }}
  SMTP_DOMAIN: {{ .Values.secrets.SMTP_DOMAIN | b64enc | quote }}
  SMTP_HOSTNAME: {{ .Values.secrets.SMTP_HOSTNAME | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.secrets.SMTP_PASSWORD | b64enc | quote }}
  SMTP_PORT: {{ .Values.secrets.SMTP_PORT | b64enc | quote }}
  SMTP_USERNAME: {{ .Values.secrets.SMTP_USERNAME | b64enc | quote }}
  SERVICE_URL: {{ .Values.secrets.SERVICE_URL | b64enc | quote }}
  OFFENDERS_API_CLIENT_ID: {{ .Values.secrets.OFFENDERS_API_CLIENT_ID | b64enc | quote }}
  OFFENDERS_API_CLIENT_SECRET: {{ .Values.secrets.OFFENDERS_API_CLIENT_SECRET | b64enc | quote }}
  MOJSSO_ID: {{ .Values.secrets.MOJSSO_ID | b64enc | quote }}
  MOJSSO_SECRET: {{ .Values.secrets.MOJSSO_SECRET | b64enc | quote }}
  MOJSSO_URL: {{ .Values.secrets.MOJSSO_URL | b64enc | quote }}
  NOMIS_API_HOST: {{ .Values.secrets.NOMIS_API_HOST | b64enc | quote }}
  NOMIS_API_CLIENT_SECRET: {{ .Values.secrets.NOMIS_API_CLIENT_SECRET | b64enc | quote }} 
  NOMIS_API_CLIENT_ID: {{ .Values.secrets.NOMIS_API_CLIENT_ID | b64enc | quote }}
  OAUTH_ENDPOINT_URL: {{ .Values.secrets.OAUTH_ENDPOINT_URL | b64enc | quote }}
  SENTRY_DSN: {{ .Values.secrets.SENTRY_DSN | b64enc | quote }}
  ZENDESK_URL: {{ .Values.secrets.SENTRY_DSN | b64enc | quote }}
  ZENDESK_USERNAME: {{ .Values.secrets.ZENDESK_USERNAME | b64enc | quote }}
  ZENDESK_TOKEN: {{ .Values.secrets.ZENDESK_TOKEN | b64enc | quote }}
