# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  aws: &aws_config
    access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
    s3_bucket_name: <%= ENV['S3_BUCKET_NAME'] %>
  geckoboard:
    api_key: <%= ENV['GECKOBOARD_API_KEY'] %>
    dataset_prefix: <%= ENV['GECKOBOARD_DATASET_PREFIX'] %>
  secret_key_base: 0515c18a50b3819aea663a1df81d30f897d63254f25d40dc0fbf81cbd568c8fe02dc130f12f3ff0f1ca2fbf6246828f65580ad308aa75f6a8c5b2d56f1ddd0f4
  nomis_api: &nomis_api_config
    host: <%= ENV['NOMIS_API_HOST'] %>
    token: <%= ENV['NOMIS_API_TOKEN'] %>
    key: <%= ENV['NOMIS_API_KEY'] %>
  zendesk_api: &zendesk_api_config
    url: <%= ENV['ZENDESK_URL'] %>
    username: <%= ENV['ZENDESK_USERNAME'] %>
    token: <%= ENV['ZENDESK_TOKEN'] %>

test:
  secret_key_base: b00b1364e73b972e9cb0f598ec47e0eaac1373d7ba7150380da281c13a828084ec8dfc6ee7240a34516d0c3c7c0a6d899752b29e1d5260c846d5de44805a401a
  nomis_api:
    host: 'http://nomis.test.com'
    # NOTE: THESE CONFIGURATION are not really used, as all the external requests should be stubbed
    token: uyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJpYXQiOjE0ODUyODU4NzgsImV4cCI6MTUxNjgyMTg3OCwiY2xpZW50IjoibXBzLXNlcmdpbyIsImtleSI6Ik1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRUtVVG10bnNrMGhoOUlIR3QxbjZmbnV0RjlmL29ISjJBSVhqa1NhSXR5ZWtaQWRnU09uUmJPWXFpMWhVZGJuVCtibG5rMzd5endicVVLTkZjekRXd25nPT0iLCJhY2Nlc3MiOlsiXlxcL25vbWlzYXBpXFwvb2ZmZW5kZXJzXFwvXFx3KyQiLCJeXFwvbm9taXNhcGlcXC9vZmZlbmRlcnNcXC9cXHcrXFwvbG9jYXRpb24kIiwiXlxcL25vbWlzYXBpXFwvb2ZmZW5kZXJzXFwvXFx3K1xcL2ltYWdlJCIsIl5cXC9ub21pc2FwaVxcL29mZmVuZGVyc1xcL1xcdytcXC9jaGFyZ2VzJCJdfQ.haiSRbfmwcsKgI4jzWP4M_diyKq7v4CJtmAfqotq0WFBtlq7tFKRzkNvS0RbIX_gkohDyQ5RVBFpPV-EOZBbZr
    key: YPdDBQEEINFieqONpi7N0dnoLW6Xmpdt6dIFuQk/Djd4tsIAttRCoAoGCCqGSM49BwEHoUQDQgAEKUTmtnsk0hh9IHGt1n6fnutF9f/oHJ2AIXjkSaItyekZAdgSOnRbKYqi1hUdbnT+blnk37yzwbqUKNFczDWrge==
  zendesk_api:
    url: 'https://mps.test.zendesk.com'
    username: 'test.user@mps.com'
    token: ABCdhphfs4KxQaLjx41qbAFRoJdNeeVlHTY4PrEp

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  aws: *aws_config
  geckoboard:
    api_key: <%= ENV['GECKOBOARD_API_KEY'] %>
    dataset_prefix: <%= ENV['GECKOBOARD_DATASET_PREFIX'] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  nomis_api: *nomis_api_config
  zendesk_api: *zendesk_api_config
