# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: docker.io/mojdigitalstudio/moving-people-safely
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  enable_whitelist: false
  host: moving-people-safely-dev.prison.service.justice.gov.uk
  cert_secret: moving-people-safely-cert
  path: /

