# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 4

image:
  repository: docker.io/mojdigitalstudio/moving-people-safely
  tag: latest
  pullPolicy: IfNotPresent
  port: 3000

ingress:
  enabled: true
  enable_whitelist: true
  host: moving-people-safely-preprod.prison.service.justice.gov.uk
  cert_secret: moving-people-safely-cert
  path: /

whitelist:
  office: "217.33.148.210/32"
  mojvpn: "81.134.202.29/32"
